name: CI

on:
  push:
    branches: [master, task4]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: cloning repo
      uses: actions/checkout@v1

    - name: Build
      run: |
        cd task4/TechProgCITemplate
        mkdir 3rdparty
        cd 3rdparty
        wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
        tar xf release-1.8.0.tar.gz
        cp -r googletest-release-1.8.0/* .
        rm -r release-1.8.0.tar.gz googletest-release-1.8.0
        cd ..
        mkdir build 
        cd build
        cmake ..
        make
    - name: check dir
      run: |
        cd task4/TechProgCITemplate/bin/
        ls -a
    - name: Test
      uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      with: 
        exec-path: 'task4/TechProgCITemplate/bin/CTestExe'
        report-path: './report.xml'
        working-directory: './'
    - name: check dir2
      run: |
        ls -a
        cat report.xml
    - name: UploadArtifacts
      run: cp task4/TechProgCITemplate/bin/C Distributive