name: CI

on:
  push:
    branches: [master, task4]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: cloning repo
      uses: actions/checkout@v1

    steps:
    - name: Build
      run: |
        cd C
        mkdir build
        cd build 
        cmake ..
        make