name: CI

on:
  push:
    branches: [master, task4]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: cloning repo
      uses: actions/checkout@v1

    - name: check directory
      run:
        ls -a

    - name: Build
      run: |
        mkdir build
        cd build 
        cmake -DTask4_SOURCE_DIR=.. ../task4/C
        make